# -*- coding: utf-8 -*-
"""Knee Osteoarthritis risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD-eNnYk4Ta7YA0kt32QqKsxX7Ls4zsW
"""

# Step 1: Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Step 2: Create a simulated clinical dataset for Knee Osteoarthritis Risk
# (In a real project, this data would be loaded from a hospital database or CSV file)
np.random.seed(42)
n_samples = 1000

data = pd.DataFrame({
    'Age': np.random.randint(40, 85, size=n_samples),
    'BMI': np.random.uniform(18.5, 40.0, size=n_samples),
    'Gender': np.random.choice([0, 1], size=n_samples), # 0: Female, 1: Male
    'Previous_Injury': np.random.choice([0, 1], size=n_samples, p=[0.7, 0.3]), # 0: No, 1: Yes
    'Knee_Pain_Score': np.random.randint(0, 10, size=n_samples) # Scale 0 to 10
})

# Define a rule for who has Osteoarthritis Risk (High BMI, Older Age, Past Injury, High Pain)
risk_formula = (
    (data['Age'] > 60).astype(int) * 2 +
    (data['BMI'] > 30).astype(int) * 3 +
    (data['Previous_Injury'] * 4) +
    (data['Knee_Pain_Score'] > 5).astype(int) * 3 +
    np.random.normal(0, 1, size=n_samples) # Add some noise
)

# Target: 1 = High Risk of Knee OA, 0 = Low/Normal Risk
data['OA_Risk'] = (risk_formula > 7).astype(int)

print("--- First 5 Rows of Patient Clinical Data ---")
print(data.head())
print("\n" + "="*50 + "\n")

# Step 3: Split data into Features (X) and Target (y)
X = data.drop('OA_Risk', axis=1)
y = data['OA_Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Train the Machine Learning Model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 5: Evaluate the Model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Knee OA Prediction Model Accuracy: {accuracy * 100:.2f}%\n")
print("Detailed Classification Report:")
print(classification_report(y_test, y_pred))

# Create a hypothetical patient profile: [Age, BMI, Gender (0:F, 1:M), Previous_Injury (0/1), Knee_Pain_Score (0-10)]
new_patient = [[65, 33.5, 0, 1, 8]]

# Make a prediction
prediction = model.predict(new_patient)
probability = model.predict_proba(new_patient)

if prediction[0] == 1:
    print(f"⚠️ RESULT: High Risk of Knee Osteoarthritis (Confidence: {probability[0][1]*100:.1f}%)")
else:
    print(f"✅ RESULT: Low/Normal Risk of Knee Osteoarthritis (Confidence: {probability[0][0]*100:.1f}%)")

import matplotlib.pyplot as plt

# Get feature importances from the model
importances = model.feature_importances_
features = X.columns

# Plot them
plt.figure(figsize=(8, 4))
plt.barh(features, importances, color='teal')
plt.xlabel("Importance Score")
plt.title("What Factors Drove the AI's Knee OA Decisions?")
plt.show()

import cv2
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files

# 1. Upload your X-ray image (if you haven't already)
print("Please upload your knee arthroplasty X-ray:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 2. Load the image in grayscale
img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

# 3. Apply CLAHE (Contrast Limited Adaptive Histogram Equalization)
# This is a standard radiology trick to make bone density and metal edges stand out clearly
clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
enhanced_img = clahe.apply(img)

# 4. Apply Edge Detection (Can help visualize bone-implant boundaries or lucency lines)
edges = cv2.Canny(enhanced_img, 100, 200)

# 5. Plot the results side-by-side
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

axes[0].imshow(img, cmap='gray')
axes[0].set_title("1. Original X-Ray")
axes[0].axis('off')

axes[1].imshow(enhanced_img, cmap='gray')
axes[1].set_title("2. Contrast Enhanced (Bone/Metal Detail)")
axes[1].axis('off')

axes[2].imshow(edges, cmap='gray')
axes[2].set_title("3. Edge Detection (Hardware Boundaries)")
axes[2].axis('off')

plt.tight_layout()
plt.show()
